# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vision.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'vision.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cvision.proto\x12\x06vision\"B\n\x0b\x42oundingBox\x12\t\n\x01x\x18\x01 \x01(\r\x12\t\n\x01y\x18\x02 \x01(\r\x12\r\n\x05width\x18\x03 \x01(\r\x12\x0e\n\x06height\x18\x04 \x01(\r\"\xd7\x01\n\x12TeletubbyDetection\x12\x16\n\x0e\x66rame_sequence\x18\x01 \x01(\r\x12\x13\n\x0bimage_width\x18\x02 \x01(\r\x12\x14\n\x0cimage_height\x18\x03 \x01(\r\x12\x10\n\x08\x64\x65tected\x18\x04 \x01(\x08\x12\x12\n\nconfidence\x18\x05 \x01(\x02\x12)\n\x0c\x62ounding_box\x18\x06 \x01(\x0b\x32\x13.vision.BoundingBox\x12-\n\x0eteletubby_type\x18\x07 \x01(\x0e\x32\x15.vision.TeletubbyType*\x97\x01\n\rTeletubbyType\x12\x1e\n\x1aTELETUBBY_TYPE_UNSPECIFIED\x10\x00\x12\x19\n\x15TELETUBBY_TYPE_YELLOW\x10\x01\x12\x18\n\x14TELETUBBY_TYPE_GREEN\x10\x02\x12\x16\n\x12TELETUBBY_TYPE_RED\x10\x03\x12\x19\n\x15TELETUBBY_TYPE_PURPLE\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vision_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TELETUBBYTYPE']._serialized_start=311
  _globals['_TELETUBBYTYPE']._serialized_end=462
  _globals['_BOUNDINGBOX']._serialized_start=24
  _globals['_BOUNDINGBOX']._serialized_end=90
  _globals['_TELETUBBYDETECTION']._serialized_start=93
  _globals['_TELETUBBYDETECTION']._serialized_end=308
# @@protoc_insertion_point(module_scope)
